POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "wind",
    "password": "wind"
}

// để có requiest mới ta ấn 3 ###
###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "wind1",
    "password": "wind"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDhhMmY5MmY2MDQyOTBlYTg2OGQ0ZGUiLCJpYXQiOjE2MTk3NzUyNTR9.Dp3wXDTQrSHFJVg6DSkTo31mhA8-IIBCKneIVoxSX6g

{
    "title": "React",
    "description": "React",
    "url": "react.com",
    "status": "TO LEARN"
    //giống với những gì chúng ta khai báo status bên Post.js, nếu không nó nhảy qua catch{} báo error
    //nếu người dùng không truyền vào thì mặc định là TO LEARN

}