POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "wind1",
    "password": "wind"
}

// để có requiest mới ta ấn 3 ###
###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "wind1",
    "password": "wind"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization:  abcxyz

{
    "title": "my first post",
    "description": "abc",
    "url": "google.com",
    "status": "LEARNING"
    //giống với những gì chúng ta khai báo status bên Post.js, nếu không nó nhảy qua catch{} báo error

}