POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "wind",
    "password": "wind"
}

// để có requiest mới ta ấn 3 ###
###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "wind1",
    "password": "wind"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDhhMmY5MmY2MDQyOTBlYTg2OGQ0ZGUiLCJpYXQiOjE2MTk5NDYzMTB9.4ihe7O0LvA7T2IbFbz6BToewwmtULpjvQXzpR4FhUSc

{
    "title": "React",
    "description": "React",
    "url": "react.com",
    "status": "TO LEARN"
    //giống với những gì chúng ta khai báo status bên Post.js, nếu không nó nhảy qua catch{} báo error
    //nếu người dùng không truyền vào thì mặc định là TO LEARN

}
###
GET  http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDhhMmY5MmY2MDQyOTBlYTg2OGQ0ZGUiLCJpYXQiOjE2MTk5NDYzMTB9.4ihe7O0LvA7T2IbFbz6BToewwmtULpjvQXzpR4FhUSc


###
PUT http://localhost:5000/api/posts/608e6953bbebc72bc842ccfa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDhhMmY5MmY2MDQyOTBlYTg2OGQ0ZGUiLCJpYXQiOjE2MTk5NDY2OTJ9.gxOd032j9at749U9s3tz-YtNR4t_jH5nzQMz-V4Jdus

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###
DELETE http://localhost:5000/api/posts/608e6953bbebc72bc842ccfa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDhhMmY5MmY2MDQyOTBlYTg2OGQ0ZGUiLCJpYXQiOjE2MTk5NDY5MDB9.Wjo-yT9gm8hey7N0PXfXwkF0k7QMeLCnkTz0MmCKLTo